//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTM
{
    using System;
    using System.Collections.Generic;
    
    public partial class gelir
    {
        public int gelirId { get; set; }
        public string gelirTanim { get; set; }
        public Nullable<int> gelirTutar { get; set; }
        public Nullable<System.DateTime> gelirDate { get; set; }
        public string gelirSearch { get; set; }
    }
}
