//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YTM
{
    using System;
    using System.Collections.Generic;
    
    public partial class gider
    {
        public int giderId { get; set; }
        public string giderTanim { get; set; }
        public Nullable<int> giderTutar { get; set; }
        public Nullable<System.DateTime> giderDate { get; set; }
        public string giderSearch { get; set; }
    }
}
